/**
 * @packageDocumentation
 * @module api.functional.products
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { PaginatedResponse } from "./../../interface/common/pagination.interface";
import type { ProductSchema } from "./../../interface/product/product.schema.interface";
import type { IProductUsecase } from "./../../interface/product/product.usecase.interface";

export * as total_count from "./total_count";

/**
 * 상품 목록 조회 API
 * 
 * 전체 상품 목록 조회
 * 
 * 추후에 쿼리를 통해 가게별, 카테고리별 등의 필터링 기준 추가
 * 
 * 추후에 쿼리를 통해 가격 낮은 순/높은 순, 인기 순 등의 정렬 기준 추가
 * 
 * @tag product
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param page query로 전달된 페이지 정보, default 1
 * @returns 페이지 정보와 함께 요청한 상품 목록
 * 
 * @controller ProductsController.findMany()
 * @path GET /products
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function findMany
    (
        connection: IConnection,
        page?: number | undefined
    ): Promise<findMany.Output>
{
    return Fetcher.fetch
    (
        connection,
        findMany.ENCRYPTED,
        findMany.METHOD,
        findMany.path(page)
    );
}
export namespace findMany
{
    export type Output = PaginatedResponse<ProductSchema.General>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/products";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(page: number | undefined): string
    {
        return `/products?${new URLSearchParams(
        {
            page
        } as any).toString()}`;
    }
}

/**
 * 상품 상세 조회 API
 * 
 * @tag product
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param product_id 상품 id
 * @returns 상품 상세 정보
 * 
 * @controller ProductsController.find()
 * @path GET /products/:product_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function find
    (
        connection: IConnection,
        product_id: string
    ): Promise<find.Output>
{
    return Fetcher.fetch
    (
        connection,
        find.ENCRYPTED,
        find.METHOD,
        find.path(product_id)
    );
}
export namespace find
{
    export type Output = ProductSchema.Detail;

    export const METHOD = "GET" as const;
    export const PATH: string = "/products/:product_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(product_id: string): string
    {
        return `/products/${encodeURIComponent(product_id)}`;
    }
}

/**
 * 상품 생성 요청 API
 * 
 * body에 포함된 store_id에 해당하는 가게에 등록된 사용자만 요청할 수 있다.
 * 
 * @tag product
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param body 상품 생성 정보
 * @returns 생성된 상품 정보
 * 
 * @controller ProductsController.create()
 * @path POST /products
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function create
    (
        connection: IConnection,
        body: IProductUsecase.CreateData
    ): Promise<create.Output>
{
    return Fetcher.fetch
    (
        connection,
        create.ENCRYPTED,
        create.METHOD,
        create.path(),
        body,
        create.stringify
    );
}
export namespace create
{
    export type Input = IProductUsecase.CreateData;
    export type Output = ProductSchema.Detail;

    export const METHOD = "POST" as const;
    export const PATH: string = "/products";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/products`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}

/**
 * 상품 수정 요청 API
 * 
 * @tag product
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param product_id 변경할 상품 id
 * @param body 변경된 상품 정보
 * @returns 변경된 상품의 상세 정보
 * 
 * @controller ProductsController.update()
 * @path PATCH /products/:product_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function update
    (
        connection: IConnection,
        product_id: string,
        body: IProductUsecase.UpdateData
    ): Promise<update.Output>
{
    return Fetcher.fetch
    (
        connection,
        update.ENCRYPTED,
        update.METHOD,
        update.path(product_id),
        body,
        update.stringify
    );
}
export namespace update
{
    export type Input = IProductUsecase.UpdateData;
    export type Output = ProductSchema.Detail;

    export const METHOD = "PATCH" as const;
    export const PATH: string = "/products/:product_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(product_id: string): string
    {
        return `/products/${encodeURIComponent(product_id)}`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}

/**
 * 상품 삭제(비활성화) 요청 API
 * 
 * @tag product
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param product_id 삭제 대상 상품의 id
 * 
 * @controller ProductsController.inActivate()
 * @path DELETE /products/:product_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function inActivate
    (
        connection: IConnection,
        product_id: string
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        inActivate.ENCRYPTED,
        inActivate.METHOD,
        inActivate.path(product_id)
    );
}
export namespace inActivate
{

    export const METHOD = "DELETE" as const;
    export const PATH: string = "/products/:product_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(product_id: string): string
    {
        return `/products/${encodeURIComponent(product_id)}`;
    }
}