/**
 * @packageDocumentation
 * @module api.functional.products.count
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * @controller ProductsController.getCount()
 * @path GET /products/count
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getCount
    (
        connection: IConnection
    ): Promise<getCount.Output>
{
    return Fetcher.fetch
    (
        connection,
        getCount.ENCRYPTED,
        getCount.METHOD,
        getCount.path()
    );
}
export namespace getCount
{
    export type Output = number;

    export const METHOD = "GET" as const;
    export const PATH: string = "/products/count";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/products/count`;
    }
}