/**
 * @packageDocumentation
 * @module api.functional.products.total_count
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * @controller ProductsController.getTotalCount()
 * @path GET /products/total-count
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getTotalCount
    (
        connection: IConnection
    ): Promise<getTotalCount.Output>
{
    return Fetcher.fetch
    (
        connection,
        getTotalCount.ENCRYPTED,
        getTotalCount.METHOD,
        getTotalCount.path()
    );
}
export namespace getTotalCount
{
    export type Output = number;

    export const METHOD = "GET" as const;
    export const PATH: string = "/products/total-count";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/products/total-count`;
    }
}